"""
schema_generator.py — 用户路径扫描引擎，生成 user_schema.yaml
V4.2 Auto-Extract 核心组件之一

功能：
- 扫描 ~/.openclaw/workspace/（递归），找出所有 .md .yaml .json .txt .sql .py 文件
- 同时扫描三个 HIPPO 版本目录（for-github / for-clawhub / for-usb）
- 读取 base_schema.yaml 作为参考骨架
- 输出 user_schema.yaml（用户实际路径清单）
"""

import os
import yaml
from pathlib import Path
from datetime import datetime

# ── 路径配置 ────────────────────────────────────────────────
USER_SCHEMA_PATH = Path(__file__).parent / "user_schema.yaml"
BASE_SCHEMA_PATH = Path(__file__).parent.parent / "task_schema" / "base_schema.yaml"

# ── 辅助函数 ────────────────────────────────────────────────
def expand_path(p: str) -> Path:
    """展开 ~ 为实际 home 目录"""
    return Path(p).expanduser()


def get_all_files_recursive(root: Path, extensions: set | None = None) -> list[Path]:
    """递归获取目录下所有指定扩展名的文件"""
    files = []
    if not root.exists():
        return files
    for item in root.rglob("*"):
        if item.is_file():
            if extensions is None or item.suffix in extensions:
                files.append(item)
    return files


# ── 核心扫描逻辑 ────────────────────────────────────────────
def scan_user_files() -> list[dict]:
    """扫描用户实际文件，返回文件列表"""
    results = []

    # 1. 扫描 workspace
    workspace = expand_path("~/.openclaw/workspace")
    extensions = {".md", ".yaml", ".yml", ".json", ".txt", ".sql", ".py"}
    for f in get_all_files_recursive(workspace, extensions):
        results.append({
            "path": str(f),
            "relative_to": str(workspace),
            "type": "workspace_file",
            "mtime": f.stat().st_mtime,
        })

    # 2. 扫描 HIPPO 项目目录（排除 assets/ 运行时生成目录）
    hippo_roots = [
        expand_path("/mnt/x/CLABIN/HIPPO/hippocampus-for-github/"),
        expand_path("/mnt/x/CLABIN/HIPPO/hippocampus-for-clawhub/"),
        expand_path("/mnt/x/CLABIN/HIPPO/hippocampus-for-usb/"),
    ]
    for hippo_root in hippo_roots:
        if not hippo_root.exists():
            continue
        for item in hippo_root.rglob("*"):
            if item.is_file() and "assets/" not in str(item):
                results.append({
                    "path": str(item),
                    "relative_to": str(hippo_root.parent),
                    "type": "hippo_file",
                    "mtime": item.stat().st_mtime,
                })

    return results


def load_base_schema() -> dict | None:
    """加载 base_schema.yaml（参考骨架），不存在则返回 None"""
    if BASE_SCHEMA_PATH.exists():
        with open(BASE_SCHEMA_PATH, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    return None


# ── 主函数 ──────────────────────────────────────────────────
def generate_user_schema(verbose: bool = True) -> dict:
    """生成 user_schema.yaml"""
    files = scan_user_files()
    base = load_base_schema()

    schema = {
        "version": "1.0",
        "description": "User actual paths — auto-generated by schema_generator.py",
        "generated_at": datetime.now().isoformat(),
        "total_files": len(files),
        "base_schema_found": base is not None,
        "paths": files,
    }

    USER_SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(USER_SCHEMA_PATH, "w", encoding="utf-8") as f:
        yaml.dump(schema, f, allow_unicode=True, default_flow_style=False)

    if verbose:
        print(f"✅ Generated {USER_SCHEMA_PATH} with {len(files)} files")
        if base is None:
            print(f"⚠️  base_schema.yaml not found at {BASE_SCHEMA_PATH}")

    return schema


# ── CLI 入口 ────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="生成 user_schema.yaml")
    parser.add_argument("--quiet", "-q", action="store_true", help="静默模式")
    args = parser.parse_args()

    generate_user_schema(verbose=not args.quiet)
